base_url = "https://card.videah.net"

[ios_banner]
title = "Videah"
subtitle = "Werewolf IRL • he/it"

[[social_links]]
name = "My Website"
url = "https://videah.net"
icon = "website.svg"

[[social_links]]
name = "Bluesky"
url = "https://bsky.app/profile/videah.net"
icon = "bluesky.svg"

[[social_links]]
name = "YouTube"
url = "https://www.youtube.com/@videah"
icon = "youtube.svg"

[[social_links]]
name = "Telegram"
url = "https://telegram.me/videah"
icon = "telegram.svg"